---
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  vars_files:
  - files/awscreds.yaml
  tasks:
  - name: Basic Provisioning
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      key_name: ansiblekey12
      group_id: sg-705f4b18
      image: ami-e60e5a89
      instance_type: t2.micro
      instance_tags: '{"Name":"{{ item }}"}'
      count: 1
      assign_public_ip: yes
      vpc_subnet_id: subnet-617bb408
      wait: true
    register: ec2
  - debug: var=item
    with_items: "{{ ec2.instances }}"
  - name: Adding host to inventory
    lineinfile:
      path: /home/ansible/aws/inventory
      regexp: '^[test]'
      insertbefore: BOF
      line: "{{ item.public_dns_name }} ansible_ssh_host={{ item.public_ip }} ansible_ssh_user=ec2-user"
    with_items: "{{ ec2.instances }}"
  - name: Adding host to group
    lineinfile:
      path: /home/ansible/aws/inventory
      regexp: '^[test]'
      insertafter: '^[test]'
      line: "{{ item.public_dns_name }}"
    with_items: "{{ ec2.instances }}"
    
