---
  - name: Basic Provisioning
    ec2:
      region: "ap-south-1"
      key_name: ansiblekey12
      group_id: sg-705f4b18
      image: ami-e60e5a89
      instance_type: t2.micro
      count: 2
      assign_public_ip: yes
      vpc_subnet_id: subnet-617bb408
      wait: true
    register: ec2
  - debug: var=item
    with_items: "{{ ec2.instances }}"
  - name: Wait for the instances to boot by checking the ssh port
    wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
    with_items: "{{ ec2.instances }}"
  - name: Adding host to inventory
    lineinfile:
      path: /home/ansible/aws/inventory
      regexp: '^[test]'
      insertbefore: BOF
      line: '{{ item.id }} ansible_ssh_host={{ item.public_ip }} ansible_ssh_user=ec2-user'
    with_items: "{{ ec2.instances }}"
  - name: Adding host to group
    lineinfile:
      path: /home/ansible/aws/inventory
      regexp: '^[test]'
      insertbefore: EOF
      line: '{{ item.id }}'
    with_items: "{{ ec2.instances }}"
    
